### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by pronouncedJerry** [pronouncedJerry/gerriediaz.com#1]
1. https://github.com/pronouncedJerry/gerriediaz.com/blob/f42e7630f82a3c577e4adf5d8e25ef755c1ded83/templates/default-template.html#L4
2. https://github.com/pronouncedJerry/gerriediaz.com/blob/f42e7630f82a3c577e4adf5d8e25ef755c1ded83/templates/default-template.html#L5

**Comment by pronouncedJerry** [comment]
hey @pinda not sure if I should have touched this file (the repo only shows after my changes). the original code has {% endblock %} for both of these, is that correct?

**Comment by pinda** [comment]
You can edit those if you like, make sure that the naming of the opening and closing block match.
